### ISSUE TITLE
Class "TomatoPHP\FilamentAccounts\Filament\Resources\AccountResource\Pages\AccountPages" not found

### ISSUE THREAD

**Issue by sardoj** [tomatophp/filament-accounts#4]
Hello,

I try to install the package with Laravel 11 and php 8.2 but I have this error

![image](https://github.com/user-attachments/assets/375aaa3d-2f26-4318-8474-3cb4346ade64)

Any idea?

**Comment by 3x1io** [comment]
fixed in the last version.
